Controllers films users
mynameisSergey/java-filmorate pull request #2
Opened 2023-03-12 20:18 UTC by mynameisSergey

2023-03-13 19:25 UTC, Fleaman777 requested changes

2023-03-13 19:25 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final HashSet<Film> films = new HashSet<>();
тип поля лучше делать более широким Set, 
так полиморфизм будет работать лучше, 
+ в случае если придется поменять реализацию на какой-нибдуь другой Set, это можно будет просто сделать в одном месте, не меняя по всему приложению

2023-03-13 19:25 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public HashSet<Film> findAllFilms() {
аналагично с возвращаемыми типами методов

2023-03-13 19:25 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            for (Film film1 : films) {
лучше стараться избегать названия с цифрами, т.к. много ясности они обычно не привносят, а значит читаемось кода ухудшается

2023-03-13 19:25 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final HashSet<User> users = new HashSet<>();
возможно более удачный вариант хранения фильмов и юзеров была бы Map, 
так удобней было бы доставать и складывать значения, 
ключ - айди, велью - значения

2023-03-13 19:25 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User put(@RequestBody User user) throws ValidationException {
put слишком общее название, лучше немного уточнить, update отлично подходит

2023-03-13 19:25 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +public class ValidationException extends Throwable {
кастомное исключение лучше наследовать от RuntimeException, 
в таком случае, при использовании этого исключения, не нужно будет каждый раз добавлять его обработку, что упростит восприятие кода

2023-03-13 19:25 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (validation(user)) {
если инвертировать условие т.е. сделать !validation(user) , то можно избавиться от лишней вложенности, что так же благоприятно скажется на чтение кода

2023-03-13 19:25 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    boolean validation(Film film) throws ValidationException {
метод можно смело делать приватным

2023-03-13 19:25 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
> +    }
хорошие тесты, все необхоимые вещи вынесены в метод с аннотацией @BeforeEach

2023-03-13 19:59 UTC, mynameisSergey commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final HashSet<Film> films = new HashSet<>();
Исправил

2023-03-13 20:00 UTC, mynameisSergey commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public HashSet<Film> findAllFilms() {
Исправил

2023-03-13 20:02 UTC, mynameisSergey commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            for (Film film1 : films) {
Исправил

2023-03-13 20:04 UTC, mynameisSergey commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final HashSet<User> users = new HashSet<>();
По возможности я пока остановился бы на этом варианте. Единственно подкорректирую по аналогии с предыдущим замечанием

2023-03-13 20:06 UTC, mynameisSergey commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User put(@RequestBody User user) throws ValidationException {
Исправил. Также исправил в контроллере фильмов

2023-03-13 20:06 UTC, mynameisSergey commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +public class ValidationException extends Throwable {
Исправил

2023-03-13 20:12 UTC, mynameisSergey commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (validation(user)) {
По возможности я оставил бы пока так

2023-03-13 20:13 UTC, mynameisSergey commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    boolean validation(Film film) throws ValidationException {
Исправил в двух контроллерах

2023-03-13 20:13 UTC, mynameisSergey commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
> +    }
Спасибо)

2023-03-14 16:44 UTC, Fleaman777 approved these changes

2023-03-14 16:44 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (validation(newFilm)) {
супер, то, что нужно

2023-03-14 16:44 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final HashSet<User> users = new HashSet<>();
хорошо, принимаю твой вариант

2023-03-14 16:44 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User update(@RequestBody User newUser) throws ValidationException {
поскольку ValidationException теперь это runtimeException, то не обязательно его пробрасывать и обрабатывать

2023-03-14 20:00 UTC, merged