Добрый день! ТЗ10
mynameisSergey/java-filmorate pull request #3
Opened 2023-03-21 21:45 UTC by mynameisSergey

2023-03-22 15:39 UTC, Fleaman777 requested changes

2023-03-22 15:39 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
если над классом добавить аннотацию @requiredargsconstructor, то можно явно не прописывать конструктор и аннотацю @autowire

относится ко всем аналогичным местам

2023-03-22 15:39 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/DateReleaseException.java
> +public class DateReleaseException extends RuntimeException {
эксепшен на каждый вид валидации, тоже не всегда хорошо, 
т.к. их может стать очень много, и их будет сложнее поддерживать: писать на каждый свой собственный хэндлер; искать более подходящий эксепшен

лучше сделать несколько более дженериковых, можно их разделить по http error кодам, которые будет возвращаться контроллерами, в случае проброса такого исключения

2023-03-22 15:39 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .collect(Collectors.toList());
хороший стрим

2023-03-22 15:39 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/Film/FilmStorage.java
> +    List<Film> showFilms();
более подходящий глагол для этих 2х методов был бы find или get, 
т.к. в результате выполнения этих методов мы получаем объекты фильмов, над котороыми потом производим различные действия 

а show - это больше о том, что бы просто взять, посмотреть и ничего с объектом не делать

2023-03-22 15:39 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/Film/InMemoryFilmStorage.java
> +    Set<String> nameFilms;
поля должны быть private

2023-03-22 15:39 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/Film/InMemoryFilmStorage.java
> +            }
много вложенных друг в друга условий ухудшает восприятие кода, 

что бы уменьшить вложенность, можно некоторые условия инвертировать, 
какие-то вынести во вспомогательные приватные методы

2023-03-22 15:39 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/Film/InMemoryFilmStorage.java
> +        LocalDate localDate = LocalDate.of(1895, 12, 28);
эту дату хорошо было бы вынести в константу с подходящим нащванием, что бы лучше понимать, за что именно означает эта дата

2023-03-22 15:39 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/User/InMemoryUserStorage.java
> +            throw new UserNotFoundException(String.format("Cannot search user by %s.", id));
лучше придеживаться единого стиля оформления, 
это относится и к месседжам/логам, они должны быть на одном языке

2023-03-22 15:39 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/User/InMemoryUserStorage.java
> +            if (userCheck != null) {
здесь тоже можешь попробовать немного переписать условия, что бы было меньше вложенности

2023-03-22 15:39 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
> +        userController.deleteUserById(friend.getId());
отличные тесты, с хорошим покрытием, молодец!

2023-03-22 19:52 UTC, mynameisSergey commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
Исправил

2023-03-22 19:54 UTC, mynameisSergey commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .collect(Collectors.toList());
Спасибо!

2023-03-22 19:59 UTC, mynameisSergey commented on src/main/java/ru/yandex/practicum/filmorate/storage/Film/FilmStorage.java
> +    List<Film> showFilms();
Исправил также и в userstorage

2023-03-22 20:01 UTC, mynameisSergey commented on src/main/java/ru/yandex/practicum/filmorate/storage/Film/InMemoryFilmStorage.java
> +    Set<String> nameFilms;
исправил

2023-03-22 20:13 UTC, mynameisSergey commented on src/main/java/ru/yandex/practicum/filmorate/storage/Film/InMemoryFilmStorage.java
> +        LocalDate localDate = LocalDate.of(1895, 12, 28);
Исправил

2023-03-22 20:20 UTC, mynameisSergey commented on src/main/java/ru/yandex/practicum/filmorate/storage/User/InMemoryUserStorage.java
> +            throw new UserNotFoundException(String.format("Cannot search user by %s.", id));
исправил

2023-03-22 20:33 UTC, mynameisSergey commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
> +        userController.deleteUserById(friend.getId());
Спасибо!

2023-03-22 20:59 UTC, mynameisSergey commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/DateReleaseException.java
> +public class DateReleaseException extends RuntimeException {
исправил, сократив количество исключений

2023-03-22 21:00 UTC, mynameisSergey commented on src/main/java/ru/yandex/practicum/filmorate/storage/Film/InMemoryFilmStorage.java
> +            }
по возможности попросил бы оставить так как есть

2023-03-22 21:00 UTC, mynameisSergey commented on src/main/java/ru/yandex/practicum/filmorate/storage/User/InMemoryUserStorage.java
> +            if (userCheck != null) {
по возможности попросил бы оставить так как есть

2023-03-23 18:19 UTC, Fleaman777 approved these changes

2023-04-02 12:50 UTC, merged