Add database
mynameisSergey/java-filmorate pull request #4
Opened 2023-04-16 16:39 UTC by mynameisSergey

2023-04-17 12:17 UTC, Fleaman777 requested changes

2023-04-17 12:17 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      }
хороший метод, что бы попробовать сделать его через стрим

2023-04-17 12:17 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return users;
этот метод так же, можно было бы сделать через стрим

2023-04-17 12:17 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/film/InMemoryFilmStorage.java
> +    Set<String> nameFilms;
поля должны быть private

2023-04-17 12:17 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/friend/FriendDbDao.java
> +        } catch (EmptyResultDataAccessException ignored) {
можно было бы добавить какой-нибудь лог, что бы эксепшен совсем бесследно не прошел

2023-04-17 12:17 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +}
тесты на контроллеры хорошие и написаны правильно, и тестируют достаточно кейсов, 
но по заданию, нужно написать тесты на каждый публичный метод dao классов

2023-04-17 12:17 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/exeption/validate/DateReleaseException.java
> +public class DateReleaseException extends RuntimeException {
эксепшен на каждый случай не всегда хорошая идея, 
лучше иметь более общие экспешены, которые будут подходить не только к 1 кейсу, но при этом и не ко всем) 
как минимум, их можно разделить по возвращаемомому коду 

когда используется много экспешенов, за ними всеми нужно следить, 
если добавляется какой-то функционал, то нужно искать подходящий эксепшен, 
или если создается новый, то писать для него хэндлер и т.д.

2023-04-17 14:22 UTC, mynameisSergey commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      }
Спасибо за оценку)

2023-04-17 14:27 UTC, mynameisSergey commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/film/InMemoryFilmStorage.java
> +    Set<String> nameFilms;
исправил

2023-04-17 14:33 UTC, mynameisSergey commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/friend/FriendDbDao.java
> +        } catch (EmptyResultDataAccessException ignored) {
Добавил

2023-04-17 15:36 UTC, mynameisSergey commented on src/main/java/ru/yandex/practicum/filmorate/exeption/validate/DateReleaseException.java
> +public class DateReleaseException extends RuntimeException {
удалил парочку Exception

2023-04-17 15:38 UTC, mynameisSergey commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return users;
Если возможно, я бы таким оставил, чтобы он соответствовал методам в классе

2023-04-18 07:48 UTC, Fleaman777 approved these changes
все хорошо, 

но 1 момент на будущее, 
хоть это и учебный проект, но все равно лучше стараться с самого начала писать правильные коммит месседжы, которые кратко бы описывали, что было сделано в коммите

самый простой подзод, начинать с клагола updated/added/removed.....

2025-02-27 19:24 UTC, merged